on:
  workflow_dispatch:
   
jobs:
  match:
    name: match students
    runs-on: ubuntu-latest
    steps:
    - name: run python script
    - uses: actions/checkout@v2
    - run: |
        python matchingProcess.py
